twig:
    file_name_pattern: '*.twig'
    date:
        timezone: 'Europe/Berlin'
    paths:
        '%kernel.project_dir%/vendor/myframework/core/resources/views': MyFrameworkCore

when@test:
    twig:
        strict_variables: true
